use std::{
    env, fs, io,
    path::{Path, PathBuf},
};

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR should be set"));
    let bundled_skills_dir = manifest_dir.join("bundled-skills");
    let bundled_workspace_dir = manifest_dir.join("bundled-workspace");

    emit_rerun_markers(&bundled_skills_dir)
        .expect("failed to configure bundled skills rerun markers");
    emit_rerun_markers(&bundled_workspace_dir)
        .expect("failed to configure bundled workspace rerun markers");

    let generated_source = generate_bundled_skills_source(&bundled_skills_dir)
        .expect("failed to generate bundled skills source");
    let generated_workspace_source = generate_bundled_workspace_source(&bundled_workspace_dir)
        .expect("failed to generate bundled workspace source");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR should be set"));
    let generated_path = out_dir.join("bundled_skills_generated.rs");
    let generated_workspace_path = out_dir.join("bundled_workspace_generated.rs");
    fs::write(&generated_path, generated_source)
        .expect("failed to write bundled skills generated source");
    fs::write(&generated_workspace_path, generated_workspace_source)
        .expect("failed to write bundled workspace generated source");

    tauri_build::build()
}

fn emit_rerun_markers(root: &Path) -> io::Result<()> {
    println!("cargo:rerun-if-changed={}", root.display());

    if !root.exists() {
        return Ok(());
    }

    let mut stack = vec![root.to_path_buf()];
    while let Some(current) = stack.pop() {
        println!("cargo:rerun-if-changed={}", current.display());

        let mut entries = fs::read_dir(&current)?.collect::<Result<Vec<_>, _>>()?;
        entries.sort_by(|left, right| left.path().cmp(&right.path()));

        for entry in entries {
            let entry_path = entry.path();
            println!("cargo:rerun-if-changed={}", entry_path.display());

            if entry.file_type()?.is_dir() {
                stack.push(entry_path);
            }
        }
    }

    Ok(())
}

fn collect_skill_directories(root: &Path) -> io::Result<Vec<PathBuf>> {
    if !root.exists() {
        return Ok(Vec::new());
    }

    let mut skill_dirs = fs::read_dir(root)?
        .collect::<Result<Vec<_>, _>>()?
        .into_iter()
        .filter_map(|entry| match entry.file_type() {
            Ok(file_type) if file_type.is_dir() => Some(Ok(entry.path())),
            Ok(_) => None,
            Err(error) => Some(Err(error)),
        })
        .collect::<Result<Vec<_>, _>>()?;

    skill_dirs.sort();
    Ok(skill_dirs)
}

fn collect_files(root: &Path) -> io::Result<Vec<PathBuf>> {
    let mut files = Vec::new();
    let mut stack = vec![root.to_path_buf()];

    while let Some(current) = stack.pop() {
        let mut entries = fs::read_dir(&current)?.collect::<Result<Vec<_>, _>>()?;
        entries.sort_by(|left, right| left.path().cmp(&right.path()));

        for entry in entries {
            let entry_path = entry.path();
            let file_type = entry.file_type()?;

            if file_type.is_dir() {
                stack.push(entry_path);
                continue;
            }

            if file_type.is_file() {
                files.push(entry_path);
            }
        }
    }

    files.sort();
    Ok(files)
}

fn generate_bundled_skills_source(root: &Path) -> io::Result<String> {
    let skill_dirs = collect_skill_directories(root)?;
    let mut output = String::from("// @generated by src-tauri/build.rs\n\n");
    let mut generated_const_names = Vec::with_capacity(skill_dirs.len());

    for (index, skill_dir) in skill_dirs.iter().enumerate() {
        let skill_name = skill_dir
            .file_name()
            .and_then(|value| value.to_str())
            .unwrap_or_default();
        let const_name = format!("BUNDLED_SKILL_{index}_FILES");
        let skill_files = collect_files(skill_dir)?;

        output.push_str(&format!("const {const_name}: &[BundledSkillFile] = &[\n"));

        for skill_file in skill_files {
            let relative_path = skill_file
                .strip_prefix(skill_dir)
                .expect("skill file should be inside the skill directory")
                .to_string_lossy()
                .replace('\\', "/");

            output.push_str(&format!(
                "    BundledSkillFile {{ relative_path: {:?}, contents: include_bytes!({:?}) }},\n",
                relative_path, skill_file
            ));
        }

        output.push_str("];\n\n");
        generated_const_names.push((skill_name.to_string(), const_name));
    }

    output.push_str("const BUNDLED_SKILLS: &[BundledSkill] = &[\n");
    for (skill_name, const_name) in generated_const_names {
        output.push_str(&format!(
            "    BundledSkill {{ name: {:?}, files: {const_name} }},\n",
            skill_name
        ));
    }
    output.push_str("];\n");

    Ok(output)
}

fn generate_bundled_workspace_source(root: &Path) -> io::Result<String> {
    let workspace_files = collect_files(root)?;
    let mut output = String::from("// @generated by src-tauri/build.rs\n\n");

    output.push_str("const BUNDLED_WORKSPACE_FILES: &[BundledWorkspaceFile] = &[\n");

    for workspace_file in workspace_files {
        let relative_path = workspace_file
            .strip_prefix(root)
            .expect("workspace file should be inside the bundled workspace directory")
            .to_string_lossy()
            .replace('\\', "/");

        output.push_str(&format!(
            "    BundledWorkspaceFile {{ relative_path: {:?}, contents: include_bytes!({:?}) }},\n",
            relative_path, workspace_file
        ));
    }

    output.push_str("];\n");
    Ok(output)
}
